name = "kids"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "raunaktr"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
